version: '2'

# The CHORDS configuration (arm) for docker-compose.
#
# It defines a MyQSL database service (chords_mysql), a CHORDS
# Ruby on Rails web server (chords_app), and a persistent
# database volume (mysql-data).
#
# This configuration is used to both build the chords image,
# and to deploy the CHORDS system. rpi-Dockerfile provides the recipe
# for the chords image.
#
# To build and upload the chords image:
#   cd <directory containing the CHORDS project>
#   docker-compose -f docker-compose-rpi.yml build
#   docker push ncareol/rpi-chords
#
# To deploy/start/stop CHORDS:
#   curl -kL https://github.com/NCAR/chords/raw/master/rpi-docker-compose.yml > docker-compose.yml
#   docker-compose pull
#   docker-compose -p chords up -d
#   docker-compose -p chords down
#
# To update a running system:
#  docker-compose pull
#  docker-compose -p chords down
#  docker-compose -p chords up -d

services:
  app:
    container_name: chords_app
    image: ncareol/rpi-chords
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - RAILS_ENV=production
      - CHORDS_DB_PW
      - SECRET_KEY_BASE=aaaaaaaaaaa
    command: bash -c "dos2unix ./chords_start.sh && chmod a+x ./chords_start.sh && ./chords_start.sh"
    ports:
        - "80:80"
    links:
      - mysql

  mysql:
    container_name: chords_mysql
    image: hypriot/rpi-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=chords_demo_user
      - MYSQL_PASSWORD=${CHORDS_DB_PW}

volumes:
  mysql-data:


